[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.1"
chumsky = { version = "0.11.1", features = ["regex"] }
inkwell = { version = "0.4", features = ["llvm15-0", "no-libffi-linking"] }
logos = "0.15.1"
